# Converts a Jupyter notebook file into markdown for display. Markdown
# cells pass through as text, code cells get an .input CSS class,
# and a trimmed selection of stdout, error and image outputs is included.

class NotebookConverter
    include ActionView::Helpers::SanitizeHelper

    def initialize(source)
        @notebook = JSON(source)
        @markdown_source = ""
    end

    def run
        @notebook["cells"].each do |cell|
            case cell["cell_type"]
            when "markdown"
                # use Array() to allow that source is just a single string
                # as apparently generated by VS Code?
                write strip_tags(Array(cell["source"]).join)
            when "code"
                write fence
                newline
                Array(cell["source"]).each do |line|
                    write line
                end
                newline
                write fence
                newline
                write "{:.input}"
                newline(2)
                # do not include outputs for now, because they might be huge
                cell["outputs"].select { |o| o["name"]=="stdout" }.each do |output|
                    take_first_and_last(output["text"], 100, 10).each do |line|
                        write indent(line)
                    end
                    write "{:.output}"
                    newline
                end
                cell["outputs"].select { |o| o["output_type"]=="error" }.each do |output|
                    write indent(output["ename"])
                    newline
                end
                cell["outputs"].select { |o| o["output_type"]=="display_data" }.each do |output|
                    begin # catch-all for when anything else than png's would be present
                        img_data = "data:image/png;base64,#{output['data']['image/png'].strip}"
                        img_desc = output["data"]["text/plain"].join
                        newline
                        write "![#{img_desc}](#{img_data})"
                        newline
                        write "{:.output}"
                        newline
                    rescue; end
                end
            end
            newline(2)
        end
        return @markdown_source
    end

    private

    def newline(n = 1)
        @markdown_source << "\n" * n
    end

    def indent(s)
        "    #{s}"
    end

    def fence
        "~~~"
    end

    def write(s)
        @markdown_source << s
    end

    def take_first_and_last(array, x, y)
        if array.length <= (x + y)
            return array
        else
            first_x_rows = array[0...x]
            last_y_rows = array[-y..-1]
            return first_x_rows + [ "...\n" ] + last_y_rows
        end
    end
end
