test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

azure:
  service: AzureStorage
  storage_account_name: <%= ::AppConfig.azure_storage_account %>
  storage_access_key: <%= ::AppConfig.azure_storage_access_key %>
  container: <%= ::AppConfig.azure_storage_container %>
